
company_name: Sahyadri Homes
company_surname: Sahyadri Homes 
phone: "+917975676745"
email: "info@sahyadriconstruction.in"
address: 2nd Main Road, Ashok Nagar, Mandya - 571401
founder: Pavan Gowda
domain: "https://nags-p.github.io/sahyadrihomes.com/"
baseurl: "/sahyadrihomes.com"
